
import Config.Koneksi;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NB01
 */
public class FormUbahPasswordProfile extends javax.swing.JFrame {

    String password;
    String username;

    /**
     * Creates new form FormUbahPassworProfile
     *
     * @param username
     * @param password
     */
    public FormUbahPasswordProfile(String username, String password) {
        initComponents();

        this.password = password;
        this.username = username;
    }

    private void setEmptyColumn() {
        tPasswordLama.setText("");
        tPasswordBaru.setText("");
        tPasswordBaru2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tPasswordLama = new javax.swing.JPasswordField();
        tPasswordBaru = new javax.swing.JPasswordField();
        tPasswordBaru2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("UBAH PASSWORD");

        jLabel2.setText("Password Lama");

        jLabel3.setText("Password Baru");

        jLabel4.setText("Ulangi Password Baru");

        tPasswordLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPasswordLamaActionPerformed(evt);
            }
        });

        tPasswordBaru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPasswordBaru2ActionPerformed(evt);
            }
        });

        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(tPasswordBaru2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tPasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tPasswordBaru2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPasswordBaru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPasswordBaru2ActionPerformed
        // To Do
    }//GEN-LAST:event_tPasswordBaru2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String passLama = tPasswordLama.getText();
        String passBaru = tPasswordBaru.getText();
        String passBaru2 = tPasswordBaru2.getText();

        if (passLama.isEmpty() || passBaru.isEmpty() || passBaru2.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "kolom harus diisi");
            return;
        }

        String passLamaHash = FormUser.hashPassword(passLama);
        String passBaruHash = FormUser.hashPassword(passBaru);

        if (!this.password.equals(passLamaHash)) {
            JOptionPane.showMessageDialog(rootPane, "password lama tidak sama dengan yang sudah ada");
            setEmptyColumn();
            return;
        }

        if (!passBaru.equals(passBaru2)) {
            JOptionPane.showMessageDialog(rootPane, "password baru yang di masukan tidak sama");
            setEmptyColumn();
            return;
        }

        try {
            try (java.sql.Statement statement = (java.sql.Statement) Koneksi.getConnection().createStatement()) {
                statement.executeUpdate("update users SET pass = '" + passBaruHash + "' WHERE username = '" + username + "' AND deleted_at is null");
            }

            JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
            dispose();

        } catch (HeadlessException | SQLException t) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Ubahi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tPasswordLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPasswordLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPasswordLamaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField tPasswordBaru;
    private javax.swing.JPasswordField tPasswordBaru2;
    private javax.swing.JPasswordField tPasswordLama;
    // End of variables declaration//GEN-END:variables
}
