
import Config.Koneksi;
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NB01
 */
public class FormKasir extends javax.swing.JFrame {

    ArrayList<String> dataBelanja = new ArrayList();
    String nama;
    String kodeBarang;
    String harga;
    String supplier;
    String stok;
    String username;
    DataTransaksiClass dataTransaksi = new DataTransaksiClass();

    /**
     * Creates new form FromKasir
     *
     * @param username
     * @param tingkatanId
     */
    public FormKasir(String username, int tingkatanId) {
        initComponents();
        enabledProperti();
        tampilTrx();
        empityInputTrx();
        tampilPencaharianDefault();

        tUsername.setText(username);
        if (tingkatanId != 1) {
            mUser.setVisible(false);
        }
        
        this.username = username;
    }

    private void enabledProperti() {
        tProduk.setEnabled(false);
        tTotalBayar.setEnabled(false);
    }

    private void empityInputTrx() {
        tProduk.setText("");
        tQuantity.setText("");
    }

    private void empityAfterTransactionSucces() {
        tStruk.setText("");
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn("Kode Barang");
        data.addColumn("Nama");
        data.addColumn("Harga");
        data.addColumn("Supplier");
        data.addColumn("Stok");

        tableData.setModel(data);
    }

    private void tampilTrx() {
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn("Nama");
        data.addColumn("Harga");
        data.addColumn("Quantity");
        data.addColumn("Jumlah Harga");

        tableTransaksi.setModel(data);
        int totalBayar = 0;

        ArrayList<TransaksiClass> red = dataTransaksi.tampilBarang();
        for (int i = 0; i < red.size(); i++) {
            data.addRow(new Object[]{
                red.get(i).namaBarang,
                red.get(i).harga,
                red.get(i).quantity,
                red.get(i).jumlah
            });

            tableTransaksi.setModel(data);
            totalBayar = totalBayar + red.get(i).jumlah;
        }

        tTotalBayar.setText(String.valueOf(totalBayar));
    }

    private DefaultTableModel tampilPencaharianDefault() {
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn("Kode Barang");
        data.addColumn("Nama");
        data.addColumn("Harga");
        data.addColumn("Supplier");
        data.addColumn("Stok");

        tableData.setModel(data);

        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        label1 = new java.awt.Label();
        tStruk = new javax.swing.JTextField();
        tProduk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tTotalBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tInputPembayaran = new javax.swing.JTextField();
        bBayar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bClearBelanjaan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tUsername = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mUser = new javax.swing.JMenuItem();
        mSupplier = new javax.swing.JMenuItem();
        mBarang = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Masukan Struk");

        tStruk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tStruk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tStrukActionPerformed(evt);
            }
        });

        tProduk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tProduk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tProdukActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Quantity");

        tQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tQuantityActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Produk");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total Bayar");

        tTotalBayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalBayarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Masukan Pembayaran");

        tInputPembayaran.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        bBayar.setBackground(new java.awt.Color(0, 204, 51));
        bBayar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bBayar.setText("Bayar");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bClearBelanjaan.setBackground(new java.awt.Color(255, 51, 51));
        bClearBelanjaan.setText("Bersihkan Belanjaan");
        bClearBelanjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearBelanjaanActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableDataFocusGained(evt);
            }
        });
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableDataMouseEntered(evt);
            }
        });
        tableData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableDataKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableDataKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTransaksi);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("APLIKASI KASIR");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Selamat datang");

        tUsername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tUsername.setForeground(new java.awt.Color(0, 204, 0));
        tUsername.setText("jLabel7");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenu1.setText("Management");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        mUser.setText("User");
        mUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserActionPerformed(evt);
            }
        });
        jMenu1.add(mUser);

        mSupplier.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        mSupplier.setText("Supplier");
        mSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(mSupplier);

        mBarang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        mBarang.setText("Barang");
        mBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBarangActionPerformed(evt);
            }
        });
        jMenu1.add(mBarang);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenu2.setActionCommand("Laporan");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem1.setText("Laporan Penjualan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setText("Analisis");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Akun");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem4.setText("Profile");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tentang");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem6.setText("Info Aplikasi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tTotalBayar)
                                    .addComponent(tInputPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(bBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(bClearBelanjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tUsername)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(tStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(tQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3))
                                    .addComponent(tTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tInputPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addComponent(bBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bClearBelanjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserActionPerformed
        FormUser barang = new FormUser();
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_mUserActionPerformed

    private void tStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tStrukActionPerformed
        DefaultTableModel data = tampilPencaharianDefault();
        try {
            Statement statement = (Statement) Koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select b.kode as kode_barang, b.nama, b.harga, b.stok, s.nama as supplier from barang b join supplier s on b.kode_supplier = s.kode where b.deleted_at is null AND (b.kode like '%" + tStruk.getText() + "%' OR b.nama like '%" + tStruk.getText() + "%')");
            while (res.next()) {
                data.addRow(new Object[]{
                    res.getString("kode_barang"),
                    res.getString("nama"),
                    res.getString("harga"),
                    res.getString("supplier"),
                    res.getString("stok")
                });

                tableData.setModel(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal Mengambil Data");
        }
        tableData.requestFocus();
    }//GEN-LAST:event_tStrukActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int i = tableData.getSelectedRow();
        if (i == -1) {
            return;
        }

        kodeBarang = (String) tableData.getValueAt(i, 0);
        nama = (String) tableData.getValueAt(i, 1);
        tProduk.setText(nama);
        harga = (String) tableData.getValueAt(i, 2);
        supplier = (String) tableData.getValueAt(i, 3);
        stok = (String) tableData.getValueAt(i, 4);
    }//GEN-LAST:event_tableDataMouseClicked

    private void tQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tQuantityActionPerformed
        String produkName = tProduk.getText();
        String quantity = tQuantity.getText();

        int quantityInt = 0;
        int stokInt = 0;
        int hargaInt = 0;

        try {
            quantityInt = Integer.parseInt(quantity);
            stokInt = Integer.parseInt(stok);
            hargaInt = Integer.parseInt(harga);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error Format Angka");
            return;
        }

        if (quantityInt <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Quantity tidak boleh kurang dari 1");
            return;
        }

        if (quantityInt > stokInt) {
            JOptionPane.showMessageDialog(rootPane, "Stok Kurang");
            return;
        }

        int jumlahInt = hargaInt * quantityInt;
        dataTransaksi.tambahTransaksi(new TransaksiClass(produkName, kodeBarang, hargaInt, quantityInt, jumlahInt));

        empityInputTrx();
        tampilTrx();
        tampilPencaharianDefault();
        tStruk.setText("");
        tStruk.requestFocus();
    }//GEN-LAST:event_tQuantityActionPerformed

    private void tTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTotalBayarActionPerformed

    private void bClearBelanjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearBelanjaanActionPerformed
        dataTransaksi.clearTransaksi();
        empityInputTrx();
        tampilTrx();
    }//GEN-LAST:event_bClearBelanjaanActionPerformed

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        ArrayList<TransaksiClass> data = dataTransaksi.tampilBarang();
        String orderNumber = UUID.randomUUID().toString();
        LocalDateTime timeNow = java.time.LocalDateTime.now();
        String username = tUsername.getText();

        String inPembayaran = tInputPembayaran.getText();
        int totalPembayaran = 0;
        for (int i = 0; i < data.size(); i++) {
            int hargaQuantity = data.get(i).harga * data.get(i).quantity;
            totalPembayaran = totalPembayaran + hargaQuantity;
        }

        int pembayaranInt;
        try {
            pembayaranInt = Integer.parseInt(inPembayaran);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Format Number Salah");
            return;
        }

        if (pembayaranInt < totalPembayaran) {
            JOptionPane.showMessageDialog(null, "Pembayaran yang di masukan kurang");
            return;
        }

        int total = 0;
        for (int i = 0; i < data.size(); i++) {
            total = data.get(i).harga * data.get(i).quantity;
            int stokInt = Integer.parseInt(stok);
            int stokUpdate = stokInt - data.get(i).quantity;

            try {
                try (java.sql.Statement statement = (java.sql.Statement) Koneksi.getConnection().createStatement()) {
                    statement.executeUpdate("update barang set stok = '" + stokUpdate + "' where kode = '" + data.get(i).kodeBarang + "' AND deleted_at is null");
                }
            } catch (HeadlessException | SQLException t) {
                JOptionPane.showMessageDialog(null, "Transaksi Gagal");
                return;
            }

            try {
                try (java.sql.Statement statement = (java.sql.Statement) Koneksi.getConnection().createStatement()) {
                    statement.executeUpdate("insert into transaksi (order_number, kode_barang, quantity, total, tanggal, username) VALUES ('" + orderNumber + "','" + data.get(i).kodeBarang + "','" + data.get(i).quantity + "','" + total + "','" + timeNow + "','" + username + "');");
                }
            } catch (HeadlessException | SQLException t) {
                JOptionPane.showMessageDialog(null, "Transaksi Gagal");
                return;
            }
        }

        int kembalian = pembayaranInt - totalPembayaran;

        FormNotifSukses notif = new FormNotifSukses(totalPembayaran, pembayaranInt, kembalian, orderNumber, dataTransaksi.tampilBarang());
        notif.setLocationRelativeTo(this);
        notif.setVisible(true);

        dataTransaksi.clearTransaksi();
        tampilTrx();
        empityAfterTransactionSucces();
        tInputPembayaran.setText("");
    }//GEN-LAST:event_bBayarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormLaporanPenjualan barang = new FormLaporanPenjualan();
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSupplierActionPerformed
        FormSupplier barang = new FormSupplier();
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_mSupplierActionPerformed

    private void mBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBarangActionPerformed
        FormBarang barang = new FormBarang();
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_mBarangActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FormAnalisis barang = new FormAnalisis();
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FormInfo barang = new FormInfo();
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FormProfile barang = new FormProfile(username);
        barang.setLocationRelativeTo(this);
        barang.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void tableDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDataKeyPressed
        int i = tableData.getSelectedRow();
        if (i == -1) {
            return;
        }

        tProduk.setText("");
        kodeBarang = (String) tableData.getValueAt(i, 0);
        nama = (String) tableData.getValueAt(i, 1);
        harga = (String) tableData.getValueAt(i, 2);
        supplier = (String) tableData.getValueAt(i, 3);
        stok = (String) tableData.getValueAt(i, 4);

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tProduk.setText(nama);
            tQuantity.requestFocus();
        }
    }//GEN-LAST:event_tableDataKeyPressed

    private void tableDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDataMouseEntered

    private void tableDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableDataFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDataFocusGained

    private void tableDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDataKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDataKeyTyped

    private void tProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tProdukActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bClearBelanjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label label1;
    private javax.swing.JMenuItem mBarang;
    private javax.swing.JMenuItem mSupplier;
    private javax.swing.JMenuItem mUser;
    private javax.swing.JTextField tInputPembayaran;
    private javax.swing.JTextField tProduk;
    private javax.swing.JTextField tQuantity;
    private javax.swing.JTextField tStruk;
    private javax.swing.JTextField tTotalBayar;
    private javax.swing.JLabel tUsername;
    private javax.swing.JTable tableData;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
