
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NB01
 */
public class FormNotifSukses extends javax.swing.JFrame {
    int total;
    int nominalPembayaran;
    int kembalian;
    String orderNumber;
    ArrayList<TransaksiClass> data;

    /**
     * Creates new form FromNotifSukses
     * @param total
     * @param nominalPembayaran
     * @param kembalian
     * @param orderNumber
     * @param data
     */
    public FormNotifSukses(int total, int nominalPembayaran, int kembalian, String orderNumber, ArrayList<TransaksiClass> data) {
        this.total = total;
        this.nominalPembayaran = nominalPembayaran;
        this.kembalian = kembalian;
        this.orderNumber = orderNumber;
        this.data = data;
        
        initComponents();
        tampilTrx();
        
        tTotal.setText(String.valueOf(this.total));
        tPembayaran.setText(String.valueOf(this.nominalPembayaran));
        tKembalian.setText(String.valueOf(this.kembalian));
        tOrderNumber.setText(this.orderNumber);
    }
    
    private void tampilTrx() {
        DefaultTableModel dataTable = new DefaultTableModel();
        DataTransaksiClass dataTransaksi = new DataTransaksiClass();
        dataTable.addColumn("Nama");
        dataTable.addColumn("Harga");
        dataTable.addColumn("Quantity");
        dataTable.addColumn("Jumlah Harga");

        tableTransaksi.setModel(dataTable);
        for (int i = 0; i < data.size(); i++) {
            dataTransaksi.tambahTransaksi(data.get(i));
        }

        ArrayList<TransaksiClass> red = dataTransaksi.tampilBarang();
        for (int i = 0; i < red.size(); i++) {
            dataTable.addRow(new Object[]{
                red.get(i).namaBarang,
                red.get(i).harga,
                red.get(i).quantity,
                red.get(i).jumlah
            });

            tableTransaksi.setModel(dataTable);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tTotal = new javax.swing.JLabel();
        tPembayaran = new javax.swing.JLabel();
        tKembalian = new javax.swing.JLabel();
        bCloseOK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tOrderNumber = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("TRANSAKSI SUKSES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("TOTAL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("PEMBAYARAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("KEMBALIAN");

        tTotal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tTotal.setForeground(new java.awt.Color(51, 153, 0));
        tTotal.setText("jLabel5");

        tPembayaran.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tPembayaran.setForeground(new java.awt.Color(0, 153, 0));
        tPembayaran.setText("jLabel6");

        tKembalian.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tKembalian.setForeground(new java.awt.Color(0, 153, 0));
        tKembalian.setText("jLabel7");

        bCloseOK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bCloseOK.setText("OK");
        bCloseOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseOKActionPerformed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTransaksi);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Order Number: ");

        tOrderNumber.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tOrderNumber.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPembayaran)
                            .addComponent(tTotal))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tKembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(bCloseOK, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(tOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tOrderNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tPembayaran))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tKembalian)
                    .addComponent(bCloseOK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseOKActionPerformed
      dispose();
    }//GEN-LAST:event_bCloseOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCloseOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tKembalian;
    private javax.swing.JLabel tOrderNumber;
    private javax.swing.JLabel tPembayaran;
    private javax.swing.JLabel tTotal;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
